### ISSUE TITLE
wait for ajax call doesn't work

### ISSUE THREAD

**Issue by barden42** [novaway/BehatCommonContext#16]
Hello,

When I fill select2 input and ajax call is thrown.
This line : $this->getSession()->wait(10000, '(0 === jQuery.active)'); should wait for the answer, but it doesn't.

There is a problem with my config or with the code ?

**Comment by jdecool** [comment]
Hello @barden42,

Thanks for reporting this issue.

I just patch the master branch to fix this issue with ajax results.

Could you confirm that the patch solve your problem ?

**Comment by barden42** [comment]
I have tested in master and it works, thanks.
I think you can create a new tag.

**Comment by jdecool** [comment]
Just tag in [v2.2.2](https://github.com/novaway/BehatCommonContext/tree/2.2.2)
