### ISSUE TITLE
I get suite has undefined steps

### ISSUE THREAD

**Issue by srlesrle** [novaway/BehatCommonContext#24]
Maybe this is not issue, but I did install your baheatcommoncontext library
behat.yml
`default:
    suites:
        default:
            contexts:
                - nwcontext:form
                - nwcontext:formstone
                - nwcontext:select2:
                    timeout: 60

    extensions:
        Laracasts\Behat\ServiceContainer\BehatExtension:
            env_path: .env.behat
        Behat\MinkExtension\ServiceContainer\MinkExtension:
            default_session: laravel
            base_url: http://localhost:8000/
            laravel: ~
            selenium2:
                browser: "firefox"
                wd_host: "http://localhost:4444/wd/hub"
        Novaway\CommonContexts\Extension: ~`

and when I add command:
`$ /d/sites/admins/voyager/adminlaravelversion55/admin/vendor/behat/behat/bin/behat -dl
default | Wanneer /^(?:|I )fill in "(?P<field>(?:[^"]|\\")*)" with "(?P<value>(?:[^"]|\\")*)" without loosing focus$/
default | Wanneer /^(?:|I )fill in "(?P<value>(?:[^"]|\\")*)" for "(?P<field>(?:[^"]|\\")*)" without loosing focus$/
default | Wanneer /^(?:|I )fill in selecter "(?P<field>(?:[^"]|\\")*)" with "(?P<value>(?:[^"]|\\")*)"$/
default | Wanneer /^(?:|I )fill in selecter "(?P<value>(?:[^"]|\\")*)" for "(?P<field>(?:[^"]|\\")*)"$/
default | Wanneer /^(?:|I )fill in dropdown "(?P<field>(?:[^"]|\\")*)" with "(?P<value>(?:[^"]|\\")*)"$/
default | Wanneer /^(?:|I )fill in dropdown "(?P<value>(?:[^"]|\\")*)" for "(?P<field>(?:[^"]|\\")*)"$/
default | Wanneer /^(?:|I )fill in select2 "(?P<field>(?:[^"]|\\")*)" with "(?P<value>(?:[^"]|\\")*)"$/
default | Wanneer /^(?:|I )fill in select2 "(?P<value>(?:[^"]|\\")*)" for "(?P<field>(?:[^"]|\\")*)"$/
default | Wanneer /^(?:|I )fill in select2 "(?P<field>(?:[^"]|\\")*)" with "(?P<value>(?:[^"]|\\")*)" and wait (?P<time>(?:[^"]|\\")*) seconds until results are loaded$/
default | Wanneer /^(?:|I )fill in select2 "(?P<value>(?:[^"]|\\")*)" for "(?P<field>(?:[^"]|\\")*)" and wait (?P<time>(?:[^"]|\\")*) seconds until results are loaded$/
default | Wanneer /^(?:|I )fill in select2 input "(?P<field>(?:[^"]|\\")*)" with "(?P<value>(?:[^"]|\\")*)"$/
default | Wanneer /^(?:|I )fill in select2 input "(?P<field>(?:[^"]|\\")*)" with "(?P<value>(?:[^"]|\\")*)" and select "(?P<entry>(?:[^"]|\\")*)"$/
default | Dan /^(?:|I )should see (?P<num>\d+) choice(?:|s) in select2 "(?P<field>(?:[^"]|\\")*)"$/
`

so it is there!

Then I add to 
`Then I fill in select2 "Name" with "key"`

This is my html:
`<span class="select2 select2-container select2-container--default select2-container--focus" dir="ltr" style="width: 62px;"><span class="selection"><span class="select2-selection select2-selection--single" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-labelledby="select2-search_key-container"><span class="select2-selection__rendered" id="select2-search_key-container" title="Id">Id</span><span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>`

but when I run behat
I get next:
` >> default suite has undefined steps. Please choose the context to generate snippets:

  [0] None
  [1] Novaway\CommonContexts\Context\FormContext
  [2] Novaway\CommonContexts\Context\FormstoneContext
  [3] Novaway\CommonContexts\Context\Select2Context
 > 3

--- Ontbrekende stappen in Novaway\CommonContexts\Context\Select2Context. Definieer ze met de volgende fragmenten:

    /**
     * @Given I am on :arg1
     */
    public function iAmOn($arg1)
    {
        throw new PendingException();
    }

    /**
     * @Then I should see :arg1
     */
    public function iShouldSee($arg1)
    {
        throw new PendingException();
    }

    /**
     * @Then I fill in :arg1 with :arg2
     */
    public function iFillInWith($arg1, $arg2)
    {
        throw new PendingException();
    }

    /**
     * @Then I press :arg1
     */
    public function iPress($arg1)
    {
        throw new PendingException();
    }

    /**
     * @Then I follow :arg1
     */
    public function iFollow($arg1)
    {
        throw new PendingException();
    }

    /**
     * @Then I sleep for :arg1 seconds
     */
    public function iSleepForSeconds($arg1)
    {
        throw new PendingException();
    }

`

Should I define all of this, because in your library it alrady exists!
So I think I shouldn't have to do it?

**Comment by jdecool** [comment]
> `>> default suite has undefined steps`

It's not an BehatCommonContext issue. The problem concern Behat configuration which doesn't detect your features files.

Specifiy location in your `behat.yml` with something like : 

```yaml
default:
    suites:
        default:
            paths:
                - "%paths.base%/tests/features"
```
